### ISSUE TITLE
Collab

### ISSUE THREAD

**Issue by atom-dispencer** [gamesmaster3000x/redfoxgroup#1]
Please add me as a collaborator if you want my help like you said you did. I already have a functioning site (image attached), however I will not give you a link to the source until you respond as to whether I am added or not (just an incentive :) I'll give the code later if you want it).

![2020-01-07](https://user-images.githubusercontent.com/46679475/71925055-1bcdb200-3188-11ea-81aa-a8e96274e02a.png)

**Comment by gamesmaster3000x** [comment]
bruh check your invites
