### ISSUE TITLE
Site overhaul

### ISSUE THREAD

**Issue by atom-dispencer** [gamesmaster3000x/redfoxgroup#9]
Replaced by #10

**Comment by Minion3665** [comment]
@GenElectrovise please create a pull request for this and **don't merge it**. This allows us to use github's 'review' feature where we can comment on pieces of your code and suggest changes/approve. It's a lot better than chatting in issues- seriously.

In answering your question: so long as it doesn't directly use a template it's good for me. We can edit it when it's actually on the site later so it fits our needs more.

**Comment by atom-dispencer** [comment]
Can do...

**Comment by Minion3665** [comment]
Replaced by #10, closed and locked
